name: Release Prod

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21


      - name: Prepare release version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          RELEASE_VERSION=${VERSION%-SNAPSHOT}
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          mvn versions:set -DnewVersion=$RELEASE_VERSION
          mvn versions:commit


      - name: Commit & Tag Release
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "chore(release): $RELEASE_VERSION"
          git tag v$RELEASE_VERSION
          git push origin main --tags


      - name: Build & Test
        run: mvn clean verify


      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/restful-api:${{ env.RELEASE_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/restful-api:latest


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to ECS Prod
        run: |
          aws ecs update-service \
            --cluster restful-prod-cluster \
            --service restful-prod-service \
            --force-new-deployment
