name: CD Staging

on:
  push:
    branches: [staging]

jobs:
  build-test-docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build & Test
        run: mvn verify
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/restful-api:homolog
            ${{ secrets.DOCKERHUB_USERNAME }}/restful-api:${{ github.sha }}
      - name: Deploy to ECS Staging
        run: |
          aws ecs update-service \
            --cluster restful-staging-cluster \
            --service restful-staging-service \
            --force-new-deployment
