name: PR Check

on:
  pull_request:

jobs:
  pr-check:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: restful
          POSTGRES_USER: restful
          POSTGRES_PASSWORD: 123
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U restful -d restful"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        env:
          SPRING_PROFILES_ACTIVE: dev
          POSTGRES_DB: restful
          POSTGRES_USER: restful
          POSTGRES_PASSWORD: 123
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: mvn clean verify -DskipTests

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=restful-api
            -Dsonar.organization=pduarteo
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
